### ISSUE TITLE
Corpera paths

### ISSUE THREAD

**Issue by saidamahmoud** [brandonstarxel/chunking_evaluation#1]
Thank you so much for the useful work.
I am using it to evaluate my chunking startgey.

I am trying to use the documents and question of Corpera you used on my own model 
and I generate the answer and chunks and i want to evaluate them (note that my model do not generate start and end index for the content).
I am trying to use "general evaluation" to evaluate. 
But i am wondering where i have to put my data paths for the question and the corresponding chunks and documents if it is needed.

I hope my question is clear 

Thanks
Saida

**Comment by brandonstarxel** [comment]
Thanks for your post Saida!

You don't need any paths if you are using the general evaluation nor does your chunker need to produce a start and end index. Could you provide a copy of your code? It should be a simple as creating a custom chunking class and putting your chunkers methods within it:

```python
from chunking_evaluation import BaseChunker, GeneralEvaluation
from chromadb.utils import embedding_functions

# Define a custom chunking class
class CustomChunker(BaseChunker):
    def split_text(self, text):
        # Your custom chunker goes here
        # It should break the text above and return the list of str (chunks) below
        # Below I have an example my_chunking_method but replace it with yours
        chunked_text = my_chunking_method(text)
        return chunked_text

# Instantiate the custom chunker and evaluation
chunker = CustomChunker()
evaluation = GeneralEvaluation()

# Choose embedding function
default_ef = embedding_functions.OpenAIEmbeddingFunction(
    api_key="OPENAI_API_KEY",
    model_name="text-embedding-3-large"
)

# Evaluate the chunker
results = evaluation.run(chunker, default_ef)

print(results)
# {'iou_mean': 0.17715979570301696, 'iou_std': 0.10619791407460026, 
# 'recall_mean': 0.8091207841640163, 'recall_std': 0.3792297991952294}
```

**Comment by saidamahmoud** [comment]
Sorry for the confusion .
In fact it is little bit complicated to write Chunker class, 
but i use Corpera generated question and documents and 
my model generate the response for each question and the first 10 chunks that similar to the responses so i want to evaluate those results. Is that possible according to your code. I have set files for the model response for each question and each include the chunks.

**Comment by brandonstarxel** [comment]
Hmmm, could you share a script of your code? 

This package is specifically for evaluating different chunking methods under top-k similarity retrieval. Therefore if you're hoping to test a whole custom retrieval process (re-rank and etc) too you unfortunately won't be able to.
