### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by jcourson8** [brandonstarxel/chunking_evaluation#3]
### Expected Behavior
The package should install and run without any ModuleNotFoundErrors.

### Actual Behavior
Encountered a ModuleNotFoundError for the 'attr' module.

### Workaround
I was able to resolve the issue by manually running:
```pip install --upgrade attrs```

**Comment by brandonstarxel** [comment]
Ah, excellent find and thank you for notifying me. I have added this to setup.py and tested it automatically installs attrs upon installing the package.
